[package]
name = "digits"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "digits-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
dialoguer = "0.10.4"
log = "0.4.17"
